name: Build and deploy Python app to Azure Web App - labtif-instaapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  serve-index:
    runs-on: ubuntu-latest

    needs:
      - build  # Garante que 'build' seja concluído antes de iniciar 'serve-index'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start a simple HTTP server
        run: |
          python -m http.server 8000
        working-directory: ${{ github.workspace }}

      - name: Make a curl request to the local server
        run: |
          curl http://localhost:8000/index.html

  deploy:
    runs-on: ubuntu-latest
    needs: [build, serve-index]
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'labtif-instaapp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3BB9B14E }}
